VERZIJA=CDX
MODUL=OS

PRGS=../main/1g/e.prg
CS=
ASMS=

SRCDOSROOT=$(BASEDOS)\\fmk\\os\\1g\\

FMK_LIBS=fmk_roba.lib fmk_svi.lib fmk_pi.lib fmk_evn.lib fmk_sec.lib fmk_rab.lib fmk_lok.lib fmk_rule.lib fmk_exp.lib

SCLIB_LIBS=sc1g_arh.lib sc1g_ba.lib sc1g_cui.lib sc1g_db.lib sc1g_os.lib sc1g_ost.lib sc1g_par.lib sc1g_pr.lib sc1g_sif.lib sc1g_sql.lib sc1g_ut.lib sc2g_app.lib sc2g_db.lib sc1g_rpt.lib sc2g_cui.lib sc1g_key.lib sc_epl2.lib sc_gvp.lib

MODUL_LIBS=os_1db.lib os_2db.lib os_1dok.lib os_1ma.lib os_2ma.lib os_1par.lib os_1rpt.lib os_1sif.lib 

include ../../fmk_lib/Makefile_clipper

