VERZIJA=CDX
MODUL=os_1rpt

SRCDOSROOT=c:\\dev\\fmk\\os\\rpt\\1g\\

PRGS=rpt_kart.prg rpt_rk1.prg rpt_rjre.prg rpt_rjk.prg rpt_rjam.prg rpt_prj.prg rpt_mnu.prg rpt_kias.prg rpt_amst.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

