VERZIJA=CDX
MODUL=os_1rpt

SRCDOSROOT=$(BASEDOS)\\fmk\\os\\rpt\\1g\\

PRGS=rpt_kart.prg rpt_rk1.prg rpt_rjre.prg rpt_rjk.prg rpt_rjam.prg rpt_prj.prg rpt_mnu.prg rpt_kias.prg rpt_amst.prg
CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper

